### ISSUE TITLE
처음엑셀회계 2.0 최신버전 있는 곳

### ISSUE THREAD

**Issue by h2dj** [ictact-coop/firstaccounting#2]
태공 블로그 (https://blog.naver.com/kwleecj) 의 "알림 및 소식" 카테고리에 있습니다

**Comment by mozodev** [comment]
데모는 그냥 동영상으로
릴리즈는 진짜로 합니다

**Comment by mozodev** [comment]
일단 조합 드루팔 파일 디렉토리에 업로드하고 링크를 땁니다. ㅎ
http://ictact.kr/sites/default/files/firstaccounting-180408.xlsm

**Comment by mozodev** [comment]
이후 https://github.com/hilkoc/vbaDeveloper 이걸 활용해서 깃헙에 레포지토리 생성 후
정식으로 릴리즈를 합니다. 이전 기여자들의 크레딧을 챙기기 위해 레거시 예전 릴리즈도 몇 개 해보죠 ㅎㅎ

**Comment by mozodev** [comment]
릴리즈 파일 확보했으니까 닫습니다.
